### PR TITLE
ENH: More complete processing history read/write support

### PR DESCRIPTION
**Pull request by larsoner**
This adds support for what I mentioned yesterday (explicit read/write and removing from the extra string), as well as supporting multiple process history entries.

### CODE REVIEW

**Comment by larsoner** [comment]
Didn't write directly so you could take a look and make sure it all makes sense before merging.

**Comment by larsoner** [comment]
push directly, that is

**Comment by agramfort** [comment]
changes look overall good. I'll let @dengemann merge and I'll comment or push on his PR directly.

thanks @Eric89GXL !

**Comment by agramfort** [comment]
btw Travis is not green...

**Comment by dengemann** [comment]
Thanks @Eric89GXL. I'll commit to my PR once I fixed the failing tests (make reading writing proc more selective to Neuromag and only if something is found, in the moment it writes a proc history everywhere).

**Pull request merged**
