### PR TITLE
FIX: Bug where no bad channels present.

### PR DESCRIPTION
**Pull request by pravsripad**

### CODE REVIEW

**Comment by dengemann** [comment]
@pravsripad Thanks for the feedback + fix!

**Comment by pravsripad** [comment]
Glad to be of help. :)

**Comment by agramfort** [comment]
@pravsripad may I ask where you are located on the planet?

**Comment by dengemann** [comment]
@agramfort I think I've already introduce @pravsripad to you a few months ago, nevermind ;-) He sits just a few offices from my office and is doing his masters thesis at the MEG lab in Jülich + works on ICA :-)

**Comment by dengemann** [comment]
> Glad to be of help. :)

Congrats! I think this was your first commit to MNE-Python ;-)

**Comment by pravsripad** [comment]
Yep, indeed it was my first. Hi @agramfort !! 

Also @dengemann  I still see this error every time I click on the epochs plot figure when I run it with tk backend, is it fixed? 

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1413, in **call**
    return self.func(_args)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 286, in button_press_event
    FigureCanvasBase.button_press_event(self, x, y, num, guiEvent=event)
  File "/usr/lib/pymodules/python2.7/matplotlib/backend_bases.py", line 1632, in button_press_event
    self.callbacks.process(s, mouseevent)
  File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 262, in process
    proxy(_args, *_kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/cbook.py", line 192, in **call**
    return mtd(_args, **kwargs)
  File "/home/prav/mne/mne-python/mne/viz.py", line 3104, in _epochs_axes_onclick
    here = vars(ax)[p['axes_handler'][0]]
TypeError: vars() argument must have __dict__ attribute

**Comment by dengemann** [comment]
So well,

> On Sep 19, 2013, at 3:29 PM, Praveen Sripad notifications@github.com wrote:
> 
> Yep, indeed it was my first. Hi @agramfort !!
> 
> Also @dengemann I still see this error every time I click on the epochs plot figure when I run it with tk backend, is it fixed?

Mhm, this is a serious backend issue. Fixing it would require lots of code uglification.
I guess quite a few viz functions don't work with the TK backend.
My take in this would be just not to use TK for interactive visualizations.
We can add a warning or an error prompting users to switch backends in such cases.

**Comment by pravsripad** [comment]
Alright. Considering it's much faster with Qt, that should do.

**Comment by dengemann** [comment]
Btw. QT is also mandatory on Linux for running the PySurfer / Mayavi related functions.
What was your problem with QT? 
The figures did not show? Actually that was not the case when we were running the scripts on your box, or was it?

**Comment by pravsripad** [comment]
Qt works fine except in all cases (mayavi, running scripts..) except for one tiny annoying detail. When I plot a figure "directly" from the ipython prompt, the window is opened in the background. I'm not sure if this can be configured otherwise, and the workaround mentioned here does not work for me http://stackoverflow.com/questions/8202228/make-matplotlib-plotting-window-pop-up-as-the-active-one.

**Pull request merged**
